### PR TITLE
Fix for Issue #17

### PR DESCRIPTION
**Pull request by m3gat0nn4ge**

### CODE REVIEW

**Comment by SimonKagstrom** [comment]
Great work! I just have one small request: Indentation in the method seems to be a mix between tabs and spaces.

I've used leading tabs in the rest of the files, so it would be nice to have that here as well. (Although I'm sure I've missed a couple of places myself!)

**Comment by m3gat0nn4ge** [comment]
Thanks Simon .. I tidied up the whitespace and replaced strtok() with split_string() .. unfortunate typo in the commit :(

**Comment by SimonKagstrom** [comment]
Thanks, merged! I suppose there is a risk that the list is empty after split_string(), which would lead to a crash later on - but let's deal with that if it turns out to be possible.

Probably it's easiest to just deal with through a panic.

**Comment by SimonKagstrom** [comment]
A small hint though: Since the original commit wasn't merged (until now), after making the second change, you can squash the two commits so that you only have a clean fix-for-issue-17 commit.

**Comment by m3gat0nn4ge** [comment]
Ah... I didn't know that, I've squashed commits before but I wasn't sure how pull requests worked .. I thought it may have been locked in

**Pull request merged**
